### ISSUE TITLE
AXP288 fixes for battery moniting

### ISSUE THREAD

**Issue by RussianNeuroMancer** [Dax89/chuwi-dev#6]
There is two approaches to get AXP288 working on BayTrail/CherryTrail devices:

First: 
https://bugzilla.kernel.org/show_bug.cgi?id=88471#c49
https://bugzilla.kernel.org/show_bug.cgi?id=88471#c55 
 
Second:
https://bugzilla.kernel.org/show_bug.cgi?id=88471#c57

**Comment by RussianNeuroMancer** [comment]
Upstream driver should be in shape since Linux 4.11.

**Comment by Dax89** [comment]
I will try to compile that kernel this week.
Thanks for the fresh news! :)

**Comment by RussianNeuroMancer** [comment]
Fixed in upstream (tested in 4.11rc1).
